name: RPG Items
main: think.rpgitems.Plugin
version: 2.3
dev-url: http://dev.bukkit.org/server-mods/rpg-items/
softdepend: [WorldGuard]
commands:
    rpgitem:
        description: RPG Items
        usage: 
        permission: rpgitem